doc:
  web:
    api:
      #Defines which cross origin urls can access what link
      crossOrigin:
        - origin: "http://localhost:8080"
          path: "/**"
        - origin: "http://5.75.149.191"
          path: "/**"
        - origin: "http://localhost:4200"
          path: "/**"
      whitelist:
        #endpoints for swagger reverse proxy
        - /auth/**
        - /v3/api-docs/**
        - /swagger-ui/**
        - /swagger-ui.html
        - /api-docs/swagger-config
  git:
    repositories:
      - id: "testRepo1"
        path: test-temp/git/repo1
      - id: "testRepo2"
        path: test-temp/git/repo2
  #     - id: "testRepoReadOnly"
  #       path: test-temp/git/repo3
  #       read-only: true
  #       db-storage: "test-temp/db/repo3"
---
doc:
  git:
    repositories:
      - id: "repo1"
        path: temp/git/repo1
      - id: "repo2"
        path: temp/git/repo2

spring:
  config:
    activate:
      on-profile: 'dev'
---
doc:
  git:
    repositories:
      - id: "java-docs"
        path: temp/git/java
      - id: "cobol-docs"
        path: temp/git/cobol
      - id: "project-docs"
        path: temp/git/project
spring:
  config:
    activate:
      on-profile: prod